### ISSUE TITLE
Getting undefined error

### ISSUE THREAD

**Issue by apertureless** [superguigui/Wagner#15]
# ⚠ Error 

`Cannot set property 'value' of undefined` 

Always at the same point 

```javascript
VignettePass.prototype.run = function(composer) {
  this.shader.uniforms.boost.value = this.params.boost; // 👈 
  this.shader.uniforms.reduction.value = this.params.reduction;
  composer.pass(this.shader);
};
```

# ♻  Environment

I am using Webpack 2 and Vue.js so my three.js component is wrapped in a vue.js component. However I don't think this is an issue.

# 💻 Code

```javascript
import Wagner from '@superguigui/wagner'
import VignettePass from '@superguigui/wagner/src/passes/vignette/VignettePass'

....
// some vue.js stuff

initPostprocessing () {
    this.composer = new Wagner.Composer(this.renderer)
    this.composer.setSize(window.innerWidth, window.innerHeight)
    this.pass = new VignettePass({
      boost: 1.0,
      reduction: 1.5
    })
},

....
```
and in my render() method

```javascript
if (this.usePostProcessing) {
  this.composer.reset()
  this.composer.render(this.scene, this.camera)
  this.composer.pass(this.pass)
  this.composer.toScreen()
} else {
  this.renderer.render(this.scene, this.camera)
}
```

**Comment by superguigui** [comment]
Hi @apertureless, thanks for this very nicely presented issue 👍 
I can't reproduce your error at the moment, which version of three.js and Wagner are you using ?

**Comment by apertureless** [comment]
The latest thats available over npm

```
"three": "^0.85.2",
"@superguigui/wagner": "^0.1.5"
```

I will see if I can make a small repo for reproduction.

**Comment by apertureless** [comment]
@superguigui 
:octocat: Repository for reproduction: https://github.com/apertureless/threejs-wagner-bug

**Comment by superguigui** [comment]
Hey man thank you for this, it was really helpful.
I figured the problem: you are using webpack for bundling and this fork of Wagner relies on glslify which is a browserify transform. If you want to use it with webpack you will have to use the proper loader, maybe you can try [this one](https://github.com/stackgl/glslify-loader) that is made from the same people than glslify. I can't help you much with webpack as I don't use it myself but it should work in theory, let me know how it goes !

**Comment by apertureless** [comment]
Yeah I thought something like this. I tried the `glslify-loader` however I think it's not working with webpack 2. At least it's not working with wagner. Anyway, thanks.
